import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { Navbar } from "@/components/layout/navbar";
import { Button } from "@/components/ui/button";
import {
  Zap,
  FileText,
  Eye,
  PenLine,
  CheckCircle2,
  ArrowRight,
  Star,
} from "lucide-react";

export default async function LandingPage() {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <div className="flex flex-col min-h-screen bg-white">
      <Navbar user={user} />

      {/* Hero */}
      <section className="flex flex-col items-center text-center px-6 pt-24 pb-20 bg-gradient-to-b from-violet-50/50 to-white">
        <div className="inline-flex items-center gap-2 rounded-full border border-violet-200 bg-violet-50 px-4 py-1.5 text-xs font-medium text-violet-700 mb-6">
          <Zap className="h-3.5 w-3.5" />
          AI-powered proposal generation
        </div>
        <h1 className="max-w-3xl text-5xl font-bold tracking-tight text-gray-900 leading-tight">
          Win more clients with proposals that{" "}
          <span className="text-violet-600">write themselves</span>
        </h1>
        <p className="mt-6 max-w-xl text-lg text-gray-600 leading-relaxed">
          ScopeProp turns your project brief into a polished, client-ready
          proposal in under 2 minutes. Scope of work, pricing, timeline — all
          generated by AI, all yours to customize.
        </p>
        <div className="mt-10 flex items-center gap-4">
          <Button size="lg" asChild>
            <Link href="/auth/signup">
              Generate your first proposal free
              <ArrowRight className="h-4 w-4" />
            </Link>
          </Button>
          <Button variant="outline" size="lg" asChild>
            <Link href="#how-it-works">See how it works</Link>
          </Button>
        </div>
        <p className="mt-4 text-sm text-gray-400">
          No credit card required · 3 free proposals
        </p>

        {/* Fake proposal preview */}
        <div className="mt-16 w-full max-w-2xl rounded-2xl border border-gray-100 bg-white shadow-xl overflow-hidden">
          <div className="flex items-center gap-2 border-b border-gray-100 px-5 py-3">
            <div className="h-3 w-3 rounded-full bg-red-400" />
            <div className="h-3 w-3 rounded-full bg-yellow-400" />
            <div className="h-3 w-3 rounded-full bg-green-400" />
            <span className="ml-3 text-xs text-gray-400">
              proposal-acme-corp.scopeprop.com
            </span>
          </div>
          <div className="p-8 text-left">
            <div className="mb-6">
              <div className="text-xs font-semibold uppercase tracking-widest text-violet-600 mb-2">
                Proposal
              </div>
              <h2 className="text-2xl font-bold text-gray-900">
                E-commerce Platform Redesign
              </h2>
              <p className="text-sm text-gray-500 mt-1">Prepared for Acme Corp · April 2025</p>
            </div>
            <div className="space-y-4">
              <div className="rounded-lg bg-gray-50 p-4">
                <div className="text-xs font-semibold text-gray-500 mb-1">EXECUTIVE SUMMARY</div>
                <p className="text-sm text-gray-700 leading-relaxed">
                  We propose a comprehensive redesign of your e-commerce platform to
                  increase conversion rate, improve mobile UX, and reduce cart abandonment
                  by an estimated 18–25%...
                </p>
              </div>
              <div className="grid grid-cols-3 gap-3">
                {["Discovery", "Design", "Development"].map((phase, i) => (
                  <div key={phase} className="rounded-lg border border-gray-100 p-3">
                    <div className="text-xs text-gray-500">Phase {i + 1}</div>
                    <div className="text-sm font-semibold text-gray-800 mt-0.5">{phase}</div>
                    <div className="text-xs text-violet-600 mt-1">{["1 week", "2 weeks", "6 weeks"][i]}</div>
                  </div>
                ))}
              </div>
              <div className="flex items-center justify-between rounded-lg bg-violet-600 px-5 py-4 text-white">
                <div>
                  <div className="text-xs opacity-70">Total Investment</div>
                  <div className="text-2xl font-bold">$18,500</div>
                </div>
                <button className="rounded-lg bg-white px-4 py-2 text-sm font-semibold text-violet-600 hover:bg-violet-50 transition-colors">
                  Sign &amp; Accept
                </button>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Social proof */}
      <section className="border-y border-gray-100 py-8 px-6">
        <div className="mx-auto max-w-5xl flex flex-col md:flex-row items-center justify-center gap-8 text-center">
          {[
            { stat: "2 min", label: "Average time to generate" },
            { stat: "3×", label: "Faster than writing manually" },
            { stat: "87%", label: "Client open rate" },
            { stat: "5,000+", label: "Proposals generated" },
          ].map(({ stat, label }) => (
            <div key={label} className="flex flex-col items-center">
              <div className="text-3xl font-bold text-gray-900">{stat}</div>
              <div className="text-sm text-gray-500 mt-1">{label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section id="features" className="py-24 px-6">
        <div className="mx-auto max-w-5xl">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900">
              Everything you need to close the deal
            </h2>
            <p className="mt-4 text-gray-500 max-w-xl mx-auto">
              From first brief to signed contract — ScopeProp handles the
              entire proposal lifecycle.
            </p>
          </div>
          <div className="grid md:grid-cols-3 gap-6">
            {[
              {
                icon: Zap,
                title: "AI Proposal Generation",
                desc: "Paste your brief, pick a tone, and get a full scope of work, deliverables, timeline, and pricing in seconds.",
              },
              {
                icon: FileText,
                title: "Smart Scope Detection",
                desc: "AI flags missing scope items and suggests deliverables you may have forgotten — protecting you from scope creep.",
              },
              {
                icon: Eye,
                title: "Client Tracking",
                desc: "Know the moment your client opens the proposal, how long they spent on each section, and when they're ready to sign.",
              },
              {
                icon: PenLine,
                title: "E-Signature Built In",
                desc: "Clients can review and sign directly on the proposal page. No third-party tools needed.",
              },
              {
                icon: CheckCircle2,
                title: "Pricing Recommendations",
                desc: "AI suggests pricing based on project type, scope complexity, and your target market.",
              },
              {
                icon: Star,
                title: "Beautiful Client Pages",
                desc: "Every proposal becomes a shareable, mobile-friendly client page that reflects your brand.",
              },
            ].map(({ icon: Icon, title, desc }) => (
              <div
                key={title}
                className="rounded-xl border border-gray-100 bg-white p-6 hover:shadow-md transition-shadow"
              >
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-violet-50 mb-4">
                  <Icon className="h-5 w-5 text-violet-600" />
                </div>
                <h3 className="font-semibold text-gray-900 mb-2">{title}</h3>
                <p className="text-sm text-gray-500 leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section id="how-it-works" className="py-24 px-6 bg-gray-50">
        <div className="mx-auto max-w-3xl text-center">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">
            From brief to signed in 4 steps
          </h2>
          <p className="text-gray-500 mb-16">
            No templates. No blank pages. Just describe your project and let AI do the work.
          </p>
          <div className="space-y-6 text-left">
            {[
              {
                step: "01",
                title: "Describe your project",
                desc: "Fill in a 5-minute form: client details, project goals, deliverables, and pricing model.",
              },
              {
                step: "02",
                title: "AI generates your proposal",
                desc: "ScopeProp writes a complete proposal — executive summary, scope, timeline, pricing breakdown, and terms.",
              },
              {
                step: "03",
                title: "Review and customize",
                desc: "Edit any section inline. Accept AI suggestions or rewrite from scratch. Your proposal, your voice.",
              },
              {
                step: "04",
                title: "Send and track",
                desc: "Share a branded link. Get notified when it's opened. Collect the signature and close the deal.",
              },
            ].map(({ step, title, desc }) => (
              <div
                key={step}
                className="flex gap-6 rounded-xl bg-white border border-gray-100 p-6"
              >
                <div className="flex-shrink-0 text-3xl font-black text-violet-100">
                  {step}
                </div>
                <div>
                  <div className="font-semibold text-gray-900 mb-1">{title}</div>
                  <div className="text-sm text-gray-500 leading-relaxed">{desc}</div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section id="pricing" className="py-24 px-6">
        <div className="mx-auto max-w-5xl">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900">Simple pricing</h2>
            <p className="mt-4 text-gray-500">
              Start free. Upgrade when you need more.
            </p>
          </div>
          <div className="grid md:grid-cols-3 gap-6">
            {[
              {
                name: "Free",
                price: "$0",
                period: "forever",
                features: [
                  "3 proposals / month",
                  "AI generation",
                  "Shareable client link",
                  "Basic tracking",
                ],
                cta: "Start free",
                href: "/auth/signup",
                highlight: false,
              },
              {
                name: "Pro",
                price: "$29",
                period: "/ month",
                features: [
                  "Unlimited proposals",
                  "E-signature",
                  "Full engagement tracking",
                  "Custom branding",
                  "PDF export",
                  "Priority AI",
                ],
                cta: "Start Pro",
                href: "/auth/signup?plan=pro",
                highlight: true,
              },
              {
                name: "Agency",
                price: "$79",
                period: "/ month",
                features: [
                  "Everything in Pro",
                  "5 team seats",
                  "Client workspaces",
                  "White-label",
                  "API access",
                  "Dedicated support",
                ],
                cta: "Start Agency",
                href: "/auth/signup?plan=agency",
                highlight: false,
              },
            ].map(({ name, price, period, features, cta, href, highlight }) => (
              <div
                key={name}
                className={`rounded-xl border p-8 flex flex-col ${
                  highlight
                    ? "border-violet-500 bg-violet-600 text-white shadow-xl"
                    : "border-gray-100 bg-white"
                }`}
              >
                <div className={`text-sm font-semibold mb-2 ${highlight ? "text-violet-200" : "text-gray-500"}`}>
                  {name}
                </div>
                <div className="flex items-end gap-1 mb-6">
                  <span className={`text-4xl font-black ${highlight ? "text-white" : "text-gray-900"}`}>
                    {price}
                  </span>
                  <span className={`text-sm mb-1 ${highlight ? "text-violet-200" : "text-gray-400"}`}>
                    {period}
                  </span>
                </div>
                <ul className="space-y-3 flex-1 mb-8">
                  {features.map((f) => (
                    <li key={f} className="flex items-center gap-2 text-sm">
                      <CheckCircle2
                        className={`h-4 w-4 flex-shrink-0 ${
                          highlight ? "text-violet-300" : "text-violet-500"
                        }`}
                      />
                      <span className={highlight ? "text-violet-100" : "text-gray-600"}>
                        {f}
                      </span>
                    </li>
                  ))}
                </ul>
                <Button
                  asChild
                  variant={highlight ? "outline" : "default"}
                  className={
                    highlight
                      ? "border-white text-white hover:bg-white hover:text-violet-600"
                      : ""
                  }
                >
                  <Link href={href}>{cta}</Link>
                </Button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-24 px-6 bg-violet-600">
        <div className="mx-auto max-w-2xl text-center text-white">
          <h2 className="text-3xl font-bold mb-4">
            Stop losing deals to slow proposals
          </h2>
          <p className="text-violet-200 mb-10">
            Freelancers and agencies that respond faster win more. Start
            generating proposals in minutes.
          </p>
          <Button
            size="lg"
            variant="outline"
            className="border-white text-white hover:bg-white hover:text-violet-600"
            asChild
          >
            <Link href="/auth/signup">
              Create your free account
              <ArrowRight className="h-4 w-4" />
            </Link>
          </Button>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-gray-100 py-8 px-6">
        <div className="mx-auto max-w-7xl flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2 text-sm font-semibold text-gray-800">
            <div className="flex h-6 w-6 items-center justify-center rounded bg-violet-600">
              <span className="text-xs font-bold text-white">S</span>
            </div>
            ScopeProp
          </div>
          <p className="text-xs text-gray-400">
            © {new Date().getFullYear()} ScopeProp. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
